repos:
    - repo: local
      hooks:
        - id: black
          name: black
          entry: black
          language: python
          args: [--config=./pyproject.toml]
          exclude: ^docs/
          types: [ python ]
          additional_dependencies:
            - black==22.6.0
        - id: flake8
          name: flake8
          entry: flake8
          language: python
          exclude: ^docs/
          types: [ python ]
          additional_dependencies:
            - flake8==4.0.1
        - id: isort
          name: isort
          entry: isort
          language: python
          types: [ python ]
          additional_dependencies:
            - isort==5.10.1